version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t hectorvmlopez/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push hectorvmlopez/todo-app:$version
  update_manifest:
      docker:
        - image: cimg/node:20.3.0
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Update manifest
            command: |
                TAG=$CIRCLE_BUILD_NUM
                ((TAG--))
                git clone https://github.com/hectorlopezv/eks-manifest-todo-app.git
                git config --global user.email "hectorvmlopez@gmail.com"
                git config --global user.name "hector lopez"
                pwd
                cd eks-manifest-todo-app
                pwd
                echo $TAG
                sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
                cat manifest/deployment.yaml
                git add .
                git commit -m "new build with imgTag build-$TAG"
                git config credential.helper 'cache --timeout=120'
                git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/hectorlopezv/eks-manifest-todo-app.git main 
workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - update_manifest:
          requires:
            - build_and_push